Pokemon/config/routes.rb
Rails.application.routes.draw do
  resources :battles

  resources :creature_locations

  resources :locations

  resources :user_creature_moves

  resources :user_creatures

  devise_for :users
  resources :moves

  resources :creatures

  get 'pages/index'

  root 'creatures#index'

end

Pokemon/app/models/battle.rb
class Battle < ActiveRecord::Base
	belongs_to :creature_location
	belongs_to :user_creature
end

Pokemon/app/models/creature.rb
class Creature < ActiveRecord::Base
	TYPES = ["Fire", "Water", "Grass", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"]
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	has_many :user_creatures
	has_many :location

	def to_s
		self.name
	end
end

Pokemon/app/models/creature_location.rb
class CreatureLocation < ActiveRecord::Base
	has_many :creatures
end

Pokemon/app/models/location.rb
class Location < ActiveRecord::Base
		has_many :creatures
end

Pokemon/app/models/move.rb
class Move < ActiveRecord::Base
	TYPES = ["Fire", "Water", "Grass", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy" ]
	def to_s
		self.name
	end
end

Pokemon/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_creatures

  def to_s
		self.email
  end
end

Pokemon/app/models/user_creature.rb
class UserCreature < ActiveRecord::Base
	belongs_to :user
	belongs_to :creature
	has_many :moves

	def to_s
		self.nickname
	end
end

Pokemon/app/models/user_creature_move.rb
class UserCreatureMove < ActiveRecord::Base
end

Pokemon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Pokemon/app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @battles = Battle.all
    respond_with(@battles)
  end

  def show
    respond_with(@battle)
  end

  def new
    @battle = Battle.new
    respond_with(@battle)
  end

  def edit
  end

  def create
    @battle = Battle.new(battle_params)
    @battle.save
    respond_with(@battle)
  end

  def update
    @battle.update(battle_params)
    respond_with(@battle)
  end

  def destroy
    @battle.destroy
    respond_with(@battle)
  end

  private
    def set_battle
      @battle = Battle.find(params[:id])
    end

    def battle_params
      params.require(:battle).permit(:creature_location_id, :user_creature_id, :user_creature_current_health_point, :creature_current_health_point)
    end
end

Pokemon/app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html

  def index
    @creatures = Creature.all
    respond_with(@creatures)
  end

  def show
    respond_with(@creature)
  end

  def new
    @creature = Creature.new
    respond_with(@creature)
  end

  def edit
  end

  def create
    @creature = Creature.new(creature_params)
    @creature.save
    respond_with(@creature)
  end

  def update
    @creature.update(creature_params)
    respond_with(@creature)
  end

  def destroy
    @creature.destroy
    respond_with(@creature)
  end

  private
    def set_creature
      @creature = Creature.find(params[:id])
    end

    def creature_params
      params.require(:creature).permit(:name, :element, :description, :sprite, :avatar)
    end
end

Pokemon/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @locations = Location.all
    respond_with(@locations)
  end

  def show
    respond_with(@location)
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    @location.save
    respond_with(@location)
  end

  def update
    @location.update(location_params)
    respond_with(@location)
  end

  def destroy
    @location.destroy
    respond_with(@location)
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :x_coordinate, :y_coordinate)
    end
end

Pokemon/app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @moves = Move.all
    respond_with(@moves)
  end

  def show
    respond_with(@move)
  end

  def new
    @move = Move.new
    respond_with(@move)
  end

  def edit
  end

  def create
    @move = Move.new(move_params)
    @move.save
    respond_with(@move)
  end

  def update
    @move.update(move_params)
    respond_with(@move)
  end

  def destroy
    @move.destroy
    respond_with(@move)
  end

  private
    def set_move
      @move = Move.find(params[:id])
    end

    def move_params
      params.require(:move).permit(:name, :pp, :element)
    end
end

Pokemon/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

Pokemon/app/controllers/user_creatures_controller.rb
class UserCreaturesController < ApplicationController
  before_action :set_user_creature, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user_creatures = UserCreature.all
    respond_with(@user_creatures)
  end

  def show
    respond_with(@user_creature)
  end

  def new
    @user_creature = UserCreature.new
    respond_with(@user_creature)
  end

  def edit
  end

  def create
    @user_creature = UserCreature.new(user_creature_params)
    @user_creature.save
    respond_with(@user_creature)
  end

  def update
    @user_creature.update(user_creature_params)
    respond_with(@user_creature)
  end

  def destroy
    @user_creature.destroy
    respond_with(@user_creature)
  end

  private
    def set_user_creature
      @user_creature = UserCreature.find(params[:id])
    end

    def user_creature_params
      params.require(:user_creature).permit(:user_id, :creature_id, :nickname)
    end
end

Pokemon/app/helpers/application_helper.rb
module ApplicationHelper
end

Pokemon/app/helpers/battles_helper.rb
module BattlesHelper
end

Pokemon/app/helpers/creature_locations_helper.rb
module CreatureLocationsHelper
end

Pokemon/app/helpers/creatures_helper.rb
module CreaturesHelper
end

Pokemon/app/helpers/locations_helper.rb
module LocationsHelper
end

Pokemon/app/helpers/moves_helper.rb
module MovesHelper
end

Pokemon/app/helpers/pages_helper.rb
module PagesHelper
end

Pokemon/app/helpers/user_creatures_helper.rb
module UserCreaturesHelper
end

Pokemon/app/views/user_creatures/_form.html.erb
<%= simple_form_for(@user_creature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :creature %>
    <%= f.input :nickname %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Pokemon/app/views/user_creatures/edit.html.erb
<h1>Editing user_creature</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_creature %> |
<%= link_to 'Back', user_creatures_path %>

Pokemon/app/views/user_creatures/index.html.erb
<h1>Listing user_creatures</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Creature</th>
      <th>Nickname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_creatures.each do |user_creature| %>
      <tr>
        <td><%= user_creature.user %></td>
        <td><%= user_creature.creature %></td>
        <td><%= user_creature.nickname %></td>
        <td><%= link_to 'Show', user_creature %></td>
        <td><%= link_to 'Edit', edit_user_creature_path(user_creature) %></td>
        <td><%= link_to 'Destroy', user_creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User creature', new_user_creature_path %>

Pokemon/app/views/user_creatures/new.html.erb
<h1>New user_creature</h1>

<%= render 'form' %>

<%= link_to 'Back', user_creatures_path %>

Pokemon/app/views/user_creatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_creature.user_id %>
</p>

<p>
  <strong>Creature:</strong>
  <%= @user_creature.creature_id %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @user_creature.nickname %>
</p>

<%= link_to 'Edit', edit_user_creature_path(@user_creature) %> |
<%= link_to 'Back', user_creatures_path %>