Pokemon/config/routes.rb
Rails.application.routes.draw do
  resources :battles

  resources :creature_locations

  resources :locations

  resources :user_creature_moves

  resources :user_creatures

  devise_for :users
  resources :moves

  resources :creatures

  get 'pages/index'

  root 'creatures#index'

end

Pokemon/app/models/battle.rb
class Battle < ActiveRecord::Base
	belongs_to :creature_location
	belongs_to :user_creature
end

Pokemon/app/models/creature.rb
class Creature < ActiveRecord::Base
	TYPES = ["Fire", "Water", "Grass", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"]
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	has_many :user_creatures
	has_many :location

	def to_s
		self.name
	end
end

Pokemon/app/models/creature_location.rb
class CreatureLocation < ActiveRecord::Base
	has_many :creatures
end

Pokemon/app/models/location.rb
class Location < ActiveRecord::Base
		has_many :creatures
end

Pokemon/app/models/move.rb
class Move < ActiveRecord::Base
	TYPES = ["Fire", "Water", "Grass", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy" ]
	def to_s
		self.name
	end
end

Pokemon/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_creatures

  def to_s
		self.email
  end
end

Pokemon/app/models/user_creature.rb
class UserCreature < ActiveRecord::Base
	belongs_to :user
	belongs_to :creature
	has_many :moves

	def to_s
		self.nickname
	end
end

Pokemon/app/models/user_creature_move.rb
class UserCreatureMove < ActiveRecord::Base
end

Pokemon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Pokemon/app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @battles = Battle.all
    respond_with(@battles)
  end

  def show
    respond_with(@battle)
  end

  def new
    @battle = Battle.new
    respond_with(@battle)
  end

  def edit
  end

  def create
    @battle = Battle.new(battle_params)
    @battle.save
    respond_with(@battle)
  end

  def update
    @battle.update(battle_params)
    respond_with(@battle)
  end

  def destroy
    @battle.destroy
    respond_with(@battle)
  end

  private
    def set_battle
      @battle = Battle.find(params[:id])
    end

    def battle_params
      params.require(:battle).permit(:creature_location_id, :user_creature_id, :user_creature_current_health_point, :creature_current_health_point)
    end
end

Pokemon/app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html

  def index
    @creatures = Creature.all
    respond_with(@creatures)
  end

  def show
    respond_with(@creature)
  end

  def new
    @creature = Creature.new
    respond_with(@creature)
  end

  def edit
  end

  def create
    @creature = Creature.new(creature_params)
    @creature.save
    respond_with(@creature)
  end

  def update
    @creature.update(creature_params)
    respond_with(@creature)
  end

  def destroy
    @creature.destroy
    respond_with(@creature)
  end

  private
    def set_creature
      @creature = Creature.find(params[:id])
    end

    def creature_params
      params.require(:creature).permit(:name, :element, :description, :sprite, :avatar)
    end
end

Pokemon/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @locations = Location.all
    respond_with(@locations)
  end

  def show
    respond_with(@location)
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    @location.save
    respond_with(@location)
  end

  def update
    @location.update(location_params)
    respond_with(@location)
  end

  def destroy
    @location.destroy
    respond_with(@location)
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :x_coordinate, :y_coordinate)
    end
end

Pokemon/app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @moves = Move.all
    respond_with(@moves)
  end

  def show
    respond_with(@move)
  end

  def new
    @move = Move.new
    respond_with(@move)
  end

  def edit
  end

  def create
    @move = Move.new(move_params)
    @move.save
    respond_with(@move)
  end

  def update
    @move.update(move_params)
    respond_with(@move)
  end

  def destroy
    @move.destroy
    respond_with(@move)
  end

  private
    def set_move
      @move = Move.find(params[:id])
    end

    def move_params
      params.require(:move).permit(:name, :pp, :element)
    end
end

Pokemon/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

Pokemon/app/helpers/application_helper.rb
module ApplicationHelper
end

Pokemon/app/helpers/battles_helper.rb
module BattlesHelper
end

Pokemon/app/helpers/creature_locations_helper.rb
module CreatureLocationsHelper
end

Pokemon/app/helpers/creatures_helper.rb
module CreaturesHelper
end

Pokemon/app/helpers/locations_helper.rb
module LocationsHelper
end

Pokemon/app/helpers/moves_helper.rb
module MovesHelper
end

Pokemon/app/helpers/pages_helper.rb
module PagesHelper
end

Pokemon/app/helpers/user_creature_moves_helper.rb
module UserCreatureMovesHelper
end

Pokemon/app/helpers/user_creatures_helper.rb
module UserCreaturesHelper
end

Pokemon/app/views/battles/_form.html.erb
<%= simple_form_for(@battle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :creature_location %>
    <%= f.association :user_creature %>
    <%= f.input :user_creature_current_health_point %>
    <%= f.input :creature_current_health_point %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Pokemon/app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render 'form' %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

Pokemon/app/views/battles/index.html.erb
<h1>Listing battles</h1>

<table>
  <thead>
    <tr>
      <th>Creature location</th>
      <th>User creature</th>
      <th>User creature current health point</th>
      <th>Creature current health point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><%= battle.creature_location_id %></td>
        <td><%= battle.user_creature_id %></td>
        <td><%= battle.user_creature_current_health_point %></td>
        <td><%= battle.creature_current_health_point %></td>
        <td><%= link_to 'Show', battle %></td>
        <td><%= link_to 'Edit', edit_battle_path(battle) %></td>
        <td><%= link_to 'Destroy', battle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle', new_battle_path %>

Pokemon/app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render 'form' %>

<%= link_to 'Back', battles_path %>

Pokemon/app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creature location:</strong>
  <%= @battle.creature_location_id %>
</p>

<p>
  <strong>User creature:</strong>
  <%= @battle.user_creature_id %>
</p>

<p>
  <strong>User creature current health point:</strong>
  <%= @battle.user_creature_current_health_point %>
</p>

<p>
  <strong>Creature current health point:</strong>
  <%= @battle.creature_current_health_point %>
</p>

<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>

Pokemon/app/views/creatures/_form.html.erb
<%= simple_form_for(@creature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :element, :as => :select, :collection => Creature::TYPES %>
    <%= f.input :description %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Pokemon/app/views/creatures/edit.html.erb
<h1>Editing creature</h1>

<%= render 'form' %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

Pokemon/app/views/creatures/index.html.erb
<h1>Listing creatures</h1>

<table>
  <thead>
    <tr>
		<th>ID</th>
      <th>Name</th>
      <th>Element</th>
      <th>Description</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creatures.each do |creature| %>
      <tr>
		  <td><%= creature.id %></td>
        <td><%= creature.name %></td>
        <td><%= creature.element %></td>
        <td><%= creature.description %></td>
        <td><%= creature.avatar %></td>
        <td><%= link_to 'Show', creature %></td>
        <td><%= link_to 'Edit', edit_creature_path(creature) %></td>
        <td><%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creature', new_creature_path %>

Pokemon/app/views/creatures/new.html.erb
<h1>New creature</h1>

<%= render 'form' %>

<%= link_to 'Back', creatures_path %>

Pokemon/app/views/creatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @creature.name %>
</p>

<p>
  <strong>Element:</strong>
  <%= @creature.element %>
</p>

<p>
  <strong>Description:</strong>
  <%= @creature.description %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @creature.avatar %>
</p>

<%= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Back', creatures_path %>

Pokemon/app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :x_coordinate %>
    <%= f.input :y_coordinate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Pokemon/app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

Pokemon/app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>X coordinate</th>
      <th>Y coordinate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.x_coordinate %></td>
        <td><%= location.y_coordinate %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

Pokemon/app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

Pokemon/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>X coordinate:</strong>
  <%= @location.x_coordinate %>
</p>

<p>
  <strong>Y coordinate:</strong>
  <%= @location.y_coordinate %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

Pokemon/app/views/moves/_form.html.erb
<%= simple_form_for(@move) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :pp %>
    <%= f.input :element, :as => :select, :collection => Move::TYPES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Pokemon/app/views/moves/edit.html.erb
<h1>Editing move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

Pokemon/app/views/moves/index.html.erb
<h1>Listing moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pp</th>
      <th>Element</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.name %></td>
        <td><%= move.pp %></td>
        <td><%= move.element %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

Pokemon/app/views/moves/new.html.erb
<h1>New move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

Pokemon/app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Pp:</strong>
  <%= @move.pp %>
</p>

<p>
  <strong>Element:</strong>
  <%= @move.element %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>